### ISSUE TITLE
can't upload eleni castro files on current develop

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-sample-data#18]
I'm not sure exactly when this broke, but dataverse-sample-data bails when run against the current develop branch:

```
data/dataverses/ecastro/datasets/this-is-my-test-dataset/files
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 84283  100    82  100 84201     68  70697  0:00:01  0:00:01 --:--:-- 70766
{'status': 'ERROR', 'message': 'NoFileException!  Serious Error! See administrator!'}
Traceback (most recent call last):
  File "create_sample_data.py", line 73, in <module>
    file_id = resp['data']['files'][0]['dataFile']['id']
KeyError: 'data'
```

```
edu.harvard.iq.dataverse.datasetutility.NoFilesException: newlyAddedFiles is empty!
        at edu.harvard.iq.dataverse.datasetutility.AddReplaceFileHelper.getSuccessResultAsJsonObjectBuilder(AddReplaceFileHelper.java:1789)
        at edu.harvard.iq.dataverse.api.Datasets.addFileToDataset(Datasets.java:1656)
```

I got the above result running this against Dataverse develop on Payara5, and against 6634-primefaces8 running on Glassfish4.

**Comment by djbrooke** [comment]
I remember adding all these files... that's the only dataset with FITS files. We made some changes to how FITS files were handled in https://github.com/IQSS/dataverse/commit/78fbb099e6723b623fee375f5a16e9db6871ac10, but that was merged back on 2/5 and I'll be surprised if it's been broken that long but 🤷‍♂ 

I created https://github.com/IQSS/dataverse-sample-data/tree/remove-fits and removed all the FITS files from that dataset in case you want to try it and narrow it down.
