### ISSUE TITLE
duplicate file error

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-sample-data#19]
`"Creating dataset tabular-sample-data.json in dataverse dataverseno", "Dataset doi:10.5072/FK2/TEIPH4 created.", "<Response [201]>", "data/dataverses/dataverseno/datasets/tabular-sample-data/files", "{'status': 'ERROR', 'message': 'This file already exists in the dataset.  Tabular_Sample_Data.txt'}"`

per @pdurbin fix is to remove https://github.com/IQSS/dataverse-sample-data/blob/bc3e57a02a7c44538e622d8d0bb6c320d2349562/dvconfig.py.sample#L6

**Comment by pdurbin** [comment]
Yeah, we do want the files @philippconzett added in f3ef7ee but I don't think we can support them until pull request https://github.com/IQSS/dataverse/pull/6924 gets merged. So commenting out that dataset for now is a good fix.
