### ISSUE TITLE
Issues running dataverse-sample-data on Python 3.5.2

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse-sample-data#2]
$ python3
Python 3.5.2 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin

This is the error that I get:

$ python3 -m venv ~/envs/dataverse-sample-data
Error: Command '['/Users/dbrooke/envs/dataverse-sample-data/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1

**Comment by djbrooke** [comment]
Trying to fix by installing xcode based on the advice here:

https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

**Comment by djbrooke** [comment]
I still get the same error following install :(

**Comment by djbrooke** [comment]
I updated to 3.7 and it worked when I specify python3.7 in 

python3.7 -m venv ~/envs/dataverse-sample-data

**Comment by pdurbin** [comment]
I feel like almost everyone hacking on Python these days has multiple versions installed and has a bit of a mess on their laptop. I am no exception and neither is the XKCD guy if https://xkcd.com/1987/ is any indication:

![python_environment](https://user-images.githubusercontent.com/21006/63042335-c242af00-be97-11e9-8af2-7b170a375dde.png)
