### ISSUE TITLE
sample datasets cannot be created in Dataverse 5.10+ due to backward incompatibility with regard to licenses

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-sample-data#30]
Multiple licenses were introduced in 5.10 with this PR:

- https://github.com/IQSS/dataverse/pull/7920

Since then, the datasets in this sample data repo can't be created. You'll get `Error parsing dataset json`

As far as I know, at minimum, you have to make this change:

```
-    "license": "CC0",
+    "license": "CC0 1.0",
```

**Comment by mreekie** [comment]
This will be included as pm.trivial. & pm.phil.

**Comment by pdurbin** [comment]
I just made the following PR to fix this:

- #33
